# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeEditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='language',
            field=models.CharField(default='', max_length=12),
        ),
    ]
